//Data types 

// In the previous section, we mentioned a little bit about data types. 
// Data or values have data types. Data types describe the characteristics of data. Data types can be divided into two:

// 1.Primitive data types
// 2.Non-primitive data types(Object References)



// Primitive Data Types

// Primitive data types in JavaScript include:

// Numbers - Integers, floats
// Strings - Any data under single quote, double quote or backtick quote
// Booleans - true or false value
// Null - empty value or no value
// Undefined - a declared variable without a value
// Symbol - A unique value that can be generated by Symbol constructor



// Non-primitive data types in JavaScript includes:

// Objects
// Arrays



// Exercises! 


                    ////// EXERCISES N1 
//1) Declare a variable named challenge and assign it to an initial value '30 Days Of JavaScript'.
let challange='30 Days Of Javascript';

//2) Print the string on the browser console using console.log()
console.log(challange);

//3) Print the length of the string on the browser console using console.log()
console.log(challange.length);

//4) Change all the string characters to capital letters using toUpperCase() method
challange.toUpperCase();

//5) Change all the string characters to lowercase letters using toLowerCase() method
challange.toLowerCase();

//6) Cut (slice) out the first word of the string using substr() or substring() method
challange.substring(1);

//7) Check if the string contains a word Script using includes() method
console.log(challange.includes('Script'));

//8) Split the string into an array using split() method
console.log(challange.split(''));

//9) Split the string 30 Days Of JavaScript at the space using split() method
console.log(challange.split(' '));

//10) Facebook, Google, Microsoft, Apple, IBM, Oracle, Amazon' split the string at the comma and change it to an array.
let test = 'Facebook, Google, Microsoft, Apple, IBM, Oracle, Amazon';
console.log(test.split(', '));

//11) Change 30 Days Of JavaScript to 30 Days Of Python using replace() method.
console.log(challange.replace('Javascript', 'Python'));

//12) What is character at index 15 in '30 Days Of JavaScript' string? Use charAt() method.
console.log(challange.charAt(15));

//13) What is the character code of J in '30 Days Of JavaScript' string using charCodeAt()
console.log(challange.charCodeAt('J'));

//14) Use indexOf to determine the position of the first occurrence of a in 30 Days Of JavaScript
console.log(challange.indexOf('a'));

//15) Use lastIndexOf to determine the position of the last occurrence of a in 30 Days Of JavaScript.
console.log(challange.lastIndexOf('a'));

//16) Use indexOf to find the position of the first occurrence of the word because in the following sentence:'You cannot end a sentence with because because because is a conjunction'
console.log('You cannot end a sentence with because because because is a conjunction'
.indexOf('because'));

//17) Use lastIndexOf to find the position of the last occurrence of the word because in the following sentence:'You cannot end a sentence with because because because is a conjunction'
console.log('You cannot end a sentence with because because because is a conjunction'
.lastIndexOf('because'));

//18) Use search to find the position of the first occurrence of the word because in the following sentence:'You cannot end a sentence with because because because is a conjunction'
console.log('You cannot end a sentence with because because because is a conjunction'.search('because'));

//19) Use trim() to remove any trailing whitespace at the beginning and the end of a string.E.g ' 30 Days Of JavaScript '.
console.log(' 30 Days Of JavaScript '.trim());

//20) Use startsWith() method with the string 30 Days Of JavaScript and make the result true
console.log(challange.startsWith(30));

//21) Use endsWith() method with the string 30 Days Of JavaScript and make the result true 
console.log(challange.endsWith('t'));

//22) Use concat() and merge '30 Days of' and 'JavaScript' to a single string, '30 Days Of JavaScript' 
console.log('30 Days of'.concat('30 Days Of JavaScript'));

//23) Use repeat() method to print 30 Days Of JavaScript 2 times
console.log(challange.repeat(2));


            //// EXERCISESS N2


console.log('________________________');

//2.1) Using console.log() print out the following statement:
console.log('There is no exercise better for the heart than reaching down and lifting people up.\' by John Holmes teaches us to help one another');

//2.2) Using console.log() print out the following quote by Mother Teresa:
console.log("Love is not patronizing and charity isn't about pity, it is about love. Charity and love are the same -- with charity you give love, so don't just give money but reach out your hand instead.")

//2.3) check if typeof '10' is exactly equal to 10. If not make it exactly equal.
console.log(Number('10')===10);

//2.4) Check if parseFloat('9.8') is equal to 10 if not make it exactly equal with 10.
console.log(Math.round(parseFloat('9.8'))===10);

//2.5) Check if 'on' is found in both python and jargon
console.log('python'.includes('on'), 'jargon'.includes('on'));

//2.6) I hope this course is not full of jargon. Check if jargon is in the sentence.
console.log('I hope this course is not full of jargon'.includes('jargon'));

//2.7) Generate a random number between 0 and 100 inclusively.
console.log(Math.round(Math.random()*101));

//2.8) Generate a random number between 50 and 100 inclusively.
console.log(Math.round(Math.random()*51)+50);

//2.9) Generate a random number between 0 and 255 inclusively.
console.log(Math.floor(Math.random()*256));

//2.10) Access the 'JavaScript' string characters using a random number. 
console.log('Javascript'[Math.floor(Math.random()*'Javascript'.length)]);

let a={
    name:'ka',
    age:'bla'
}

let b=a;


console.log(b);

console.log(parseFloat('9.8'));